#Porta deste Microservice
server:
  port: ${PORT:9020}

#Configuracoes relacionadas ao registro no eureka
eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
  client:
    serviceUrl:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka/}
      healthcheck:
        enabled: true

#Configuracoes relacionadas ao Actuator
info:
  app:
    name:@project.name@
    description:@project.description@
    version:@project.version@